//  generated by wirenboard-mqtt-proxy

defineVirtualDevice("mqtt-proxy", {
  title: "MQTT Proxy",
  cells: {
    config:     { type: "text",   value: "",  readonly: false, forceDefault: true},
    uptime:     { type: "text",   value: "",  readonly: false, forceDefault: true},
    connected:  { type: "value",  value: 0,   readonly: false, forceDefault: true},
    topics:     { type: "value",  value: 0,   readonly: false, forceDefault: true},
    error:      { type: "text",   value: "",  readonly: false, forceDefault: true},
  }
});
